services:
  mysql:
    image: mysql:8.0
    container_name: sky-mysql
    environment:
      MYSQL_DATABASE: sky_take_out
      MYSQL_USER: app
      MYSQL_PASSWORD: app123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - sky_mysql_data:/var/lib/mysql

volumes:
  sky_mysql_data: